### ISSUE TITLE
Comunication port cannot be changed unlike OSDK 4.1.0

### ISSUE THREAD

**Issue by MH2033** [dji-sdk/Payload-SDK#32]
Hello
In our project we're using /dev/tty/dev/acm0 as our UART port to communicate with the drone. The project was built on top of OSDK 4.1.0 and we could specify the port in "userconfig.txt".After trying to run the samples of the new payload SDK, the SDK seems to automatically look for /dev/tty/USB0 and that cannot be changed. Any solutions?

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/59558'>Zendesk ticket #59558</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/59558'>Zendesk ticket #59558</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

The UART port can be changed in code file: hal_uart.h
https://github.com/dji-sdk/Payload-SDK/blob/7b5f853e877d0f2443bcab8f57101afe12a9a14b/samples/sample_c/platform/linux/manifold2/hal/hal_uart.h#L48

And there is a link for simple guidance:
https://sdk-forum.dji.net/hc/en-us/articles/4408437830041-PSDK-3-0-version-OSDK-OSDK-5-0-introduction-and-guidance

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
<br><p><em><small>°°°</small></em></p>

**Comment by MH2033** [comment]
Thank you this solved the issue
