### ISSUE TITLE
MOP server cannot be initialized on osdk port

### ISSUE THREAD

**Issue by MH2033** [dji-sdk/Payload-SDK#34]
The following error message will be generated when trying to initialize MOP server sample on extension port:

![Screenshot 2022-03-16 144726](https://user-images.githubusercontent.com/5557100/158578457-867c5f02-dcb2-464b-90a8-7d16bf71c89e.jpg)

Connection is established via expansion module and uart plus usb

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/61627'>Zendesk ticket #61627</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/61627'>Zendesk ticket #61627</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

Sorry for the inconvenience, this problem is a bug of PSDK 3.0, and we have submited to the relevant department for fixing. If there is an update, we will push it to GitHub.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
<br><p><em><small>°°°</small></em></p>

**Comment by MH2033** [comment]
Thank you for your answer. Can you give us an estimation on when this bug will be fixed? I'm asking since our product relies heavily on this feature.

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/61627'>Zendesk ticket #61627</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

Sorry, this may not be able to tell you the specific time at present, we will update and submit this issue again, and we will ask the relevant departments to fix it as soon as possible.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
<br><p><em><small>°°°</small></em></p>

**Comment by MH2033** [comment]
Thank you for your answer
Regards

**Comment by MH2033** [comment]
Any updates regarding this issue?

**Comment by samanazadpour** [comment]
@dji-dev we are waiting for you guys. would you please give us an update? Our application is using MOP server and at the moment it is not working! we need to know what is the road map and when it will be fixed.

**Comment by MH2033** [comment]
This issue seems to be resolved in release 3.2
