### ISSUE TITLE
Max Frequency for RTK and GPS location topics

### ISSUE THREAD

**Issue by MH2033** [dji-sdk/Payload-SDK#38]
Hi
I was reading the dji_fc_subscription.h file and couldn't find any info about the max subscription freq for getting RTK and GPS location. Can you provide a reference?

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/62114'>Zendesk ticket #62114</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/62114'>Zendesk ticket #62114</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

The max subscription freq for getting RTK and GPS location is 5HZ.
We will add notes for those topic, you can refer to the relevant introduction in OSDK 4.1 first, the telemetry subscription frequency is the same
https://github.com/dji-sdk/Onboard-SDK/blob/master/osdk-core/api/inc/dji_telemetry_doc.hpp

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
<br><p><em><small>°°°</small></em></p>

**Comment by MH2033** [comment]
Thank you for your response. 
I saw the link you mentioned before and there's contradiction in the docs. As you can see in the following link it is stated that max subscription freq for GPS and RTK location is 50Hz :  https://developer.dji.com/onboard-sdk/documentation/guides/component-guide-telemetry.html
![image](https://user-images.githubusercontent.com/5557100/160372642-84987139-62c8-4ba3-b090-d2b0f369bce7.png)

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/62114'>Zendesk ticket #62114</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

The webpage has updated, and please refer to the code file or this link for specific TOPIC:
https://developer.dji.com/onboard-api-reference/group__telem.html

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
<br><p><em><small>°°°</small></em></p>

**Comment by MH2033** [comment]
Thank you for sharing this link.
Regards
